# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "stlviewerwinit"
version = "0.0.1"
edition = "2021"


[dependencies]
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.17"
cgmath = "0.18"
pollster = "0.3.0"
